### ISSUE TITLE
Multiplatform support(iOS + Android) for push notification

### ISSUE THREAD

**Issue by suniliosdev** [twilio/voice-quickstart-objc#109]
Can we use FCM for push notification in VoIP voice call? if I use apn credential its working fine but if I try to use FCM for iOS I am not getting push notification while making call.

If I have to use apn only(as mention in step https://github.com/twilio/voice-quickstart-swift#8-create-a-push-credential-with-your-voip-service-certificate) what should I do if I want to work on both iOS and android.

which value should we use as PUSH_CREDENTIAL_SID on server?

**Comment by bobiechen-twilio** [comment]
Hi @SunilSpaceo 

The Programmable Voice iOS SDK requires a VoIP Service certificate in order to enable the incoming call notifications. It is different from the regular APNS certificate so you will need to follow the quickstart steps to generate one and create Push Credential with the credentials.

Currently Voice iOS SDK does not support notifications using FCM.

thanks
-bobie

**Comment by bobiechen-twilio** [comment]
@SunilSpaceo 

To be more accurate, FCM does support APN service, but not for Apple VoIP Service at the moment.

**Comment by suniliosdev** [comment]
Thanks for your reply. I understand, we have to use VoIP Service certificate for iOS but which value should we use as PUSH_CREDENTIAL_SID on server? 
if I set that value as FCM push credential, it will work for Android but not for iOS
if I set that value as APN push credential, it will work for iOS but not for Android
so which value to set if I want to support for both iOS and Android.

Is there a way we can set PUSH_CREDENTIAL_SID value dynamically so it works for both platform?

**Comment by bobiechen-twilio** [comment]
Hi @SunilSpaceo 

One way is to embed additional platform info in the http request URL parameter list. For example
```
https://my.server.ai/accessToken?platform=ios_sandbox&duration=86400
```
and check the value of the `platform` parameter on your access token server endpoint, then determine which push credential sid to put in the access token.

**Comment by GBR-422777** [comment]
@bchen-twilio 

platform ios_sandbox in this case is the destination platform or source?

**Comment by bobiechen-twilio** [comment]
@GBR-422777 everything embedded in the access token is meant for the local client.

**Comment by GBR-422777** [comment]
Okay @bchen-twilio ,

So we have implemented the solution you suggested above regarding changing the source.

Result is:
- Android to Android works
- iOS to Android works
- Android to iOS does not work.

For the case of Android to iOS sometimes we get the following error:
52143 The push notification was rejected by APNs
- The device token does not match the specified topic."

Other times it does not give any error at all as the calls remains Undialed then it switches to Un Answered

Any clue?

**Comment by bobiechen-twilio** [comment]
@GBR-422777 
Is the iOS app (under the same bundle ID) using multiple Push Credential SIDs? Please make sure you follow the [push credential setup guide](https://github.com/twilio/voice-quickstart-objc#8-create-a-push-credential-with-your-voip-service-certificate) for the iOS app.

**Comment by GBR-422777** [comment]
@bchen-twilio ,

Yes we followed this twice.

**Comment by GBR-422777** [comment]
@bchen-twilio 
We are following the steps again and in the cert.pem has two ----START  CERTIFICATE----- ----END CERTIFICATE-----
First for VoIP
Second for Push Notifications.


Key.pem is only being generated when we put a passphrase otherwise it shows an error.
it contains the RSA key

Any clue?

**Comment by bobiechen-twilio** [comment]
@GBR-422777 
To be safe I'd recommend using separate CSRs to generate different certificates for regular APNS and VoIP service.
To tackle the notification delivery problem we are seeing here:
- Please check if the app is receiving any PushKit notification at different states (active/backgrounded/terminated). You can use the mac OS Console app to view the device log when the phone is not attached to the Xcode debugger.
- Please provide us your Twilio Account SID and the Push Credential SIDs used for your iOS Voice application so that I can check with the server team and see if they can dig up any insights regarding the delivery failure when it happens. (You should be able to find my work email. Please do not disclose any of your Twilio credentials in the public forum)

Thanks
-bobie

**Comment by GBR-422777** [comment]
@bchen-twilio, 

Issue solved.
We regenerated all of the certificates including the provisioning profile. 


Thank you for your help and guidance.

**Comment by bobiechen-twilio** [comment]
@GBR-422777 glad to hear that! Thanks for providing useful debugging info.
Cheers 🍻
