### ISSUE TITLE
Call screen  is minimised

### ISSUE THREAD

**Issue by jamesawer3** [twilio/voice-quickstart-objc#132]
Hi,
 I'm using twiliovoice in my app I'm registering the device token when the app starts itself (i.e) in appdelegate. In registration there is no error's app is getting registered successfully and call is coming. The problem comes here since im using iOS the native call screen is coming so if I attend the call the native calling screen is getting hidden and it can't be opened, the green bar comes up and even if I press the green bar in notification area, its redirecting me to app screen not to calling screen. The problem is after attending the it's default going to loudspeaker I can't further turn off the speaker or mute the call or any functions related to call.

**Comment by piyushtank** [comment]
@jamesawer3 Thanks for reaching out. Can you answer following questions in order to debug the problem further - 
1. The Voice SDK version, iOS version and the iOS device
2. Are you using CallKit in your app?
3. When you said incoming native call, did you mean a PSTN (or other app's VoIP)  call or an incoming Voice SDK call ? If its Voice SDK call on CallKit UI, you can go to app from by clicking the app button on CallKit UI.
4. We have changed Audio APIs in 3.x Preview releases. Once I have have the versioning information of SDK, I can provide how to use the SDK to switch audio routes using the SDK APIs.

**Comment by bobiechen-twilio** [comment]
Hi @jamesawer3 

It is a CallKit designed behavior that the call will be redirected to the app itself when the phone is not locked, e.g. answering CallKit incoming call when the app is in the foreground or background. You will find the system Call UI in the recently active app list when you double-tap the home button.

TwilioVoice SDK also has APIs to allow your app to perform all the functionalities in the system call UI.

Thanks
-bobie

**Comment by bobiechen-twilio** [comment]
Hi @jamesawer3 
I am closing this ticket since there hasn't been activity for a while and assuming you are satisfied with the answer. Please feel free to reach to us if you run into any issue or question in the future.

Thanks!
-bobie
