### ISSUE TITLE
Interoperability with TwilioClient

### ISSUE THREAD

**Issue by alexiss03** [twilio/voice-quickstart-objc#17]
Hi! This is more of a question than an issue. Do you support interoperability between TwilioClient and TwilioVoiceClient? Currently, our app deployed in App Store is using TwilioClient but we want to migrate to TwilioVoiceClient. Is their a way for us to establish a voice call connection between the two versions? If not, will you support this in the future? 

Thanks,
Alexis

**Comment by bobiechen-twilio** [comment]
Hi @alexiss03,
Bobie here from the iOS SDK team.
Good question. Are you asking about the interoperability for the two versions to coexist inside the same app and use the APIs of both of them, or are you asking specifically if two the apps, one version with the TwilioClient SDK and the other with the TwilioVoiceClient framework, are able to establish calls with each other?
The answer for the second one is affirmative. As long as the mobile clients are under the same Twilio Voice account, they are able to connect to each other without problem.
For both versions of SDK to coexist in the same app, honestly we haven't tried since the Programmable Voice iOS SDK (TwilioVoiceClient framework) is designed to be the successor of the 1.2 TwilioClient due to the fact that Apple stopped the support of background VoIP socket, which is required by the TwilioClient SDK to keep the SIP registration for incoming calls, especially when the app is in the background.

**Comment by alexiss03** [comment]
I was asking for the second scenario. Thanks for clearing things up @bchen-twilio.

**Comment by bobiechen-twilio** [comment]
Cool, but we still recommend that you migrate as fast as you can as I mentioned that with iOS 9 and later the TwilioClient SDK won't work really well.
Thanks again for choosing the Twilio Voice SDK and please feel free to leave us feedback any time.

bobie

**Comment by bobiechen-twilio** [comment]
Hi @alexiss03,
I am going to close this ticket. Please don't hesitate to contact us if you run into any issue or have any question using the Twilio Voice SDK in the future.
Thank you very much!
