### ISSUE TITLE
Error when I try to register VOIP Pushes

### ISSUE THREAD

**Issue by homanp** [twilio/voice-quickstart-objc#7]
Hi,

Getting this error when trying to register for push notifications:

`Error Domain=com.twilio.TVONotificationClient Code=31301 "Failed to register. Code: 5." UserInfo={NSLocalizedDescription=Failed to register. Code: 5.}`

I've created credentials as per your guide and everything seems to be fine. 

But get this error. Any ideas?

**Comment by homanp** [comment]
This was fixed by adding an IDENTITY to the accessToken.

**Comment by ranjitsoni** [comment]
Hi,

Where to add IDENTITY to the accessToken, could you please share code snippet.

Thanks

**Comment by bobiechen-twilio** [comment]
Hi @ranjitsoni,
First of all, thank you for choosing the Twilio Programmable Voice iOS SDK.
[This line](https://github.com/twilio/voice-quickstart-server-python/blob/master/server.py#L31) is the python example of using the Twilio helper library to generate the access token with specified identity.
You will also find helper libraries of different languages at the bottom of this [getting-started guide](https://www.twilio.com/docs/api/voice-sdk/ios/getting-started).
The rest you will need to do is to add proper HTTP request parameters in order to carry the identity from your mobile application to the token vending server.
Please let us know if this helps. Thanks again!

bobie

**Comment by miken01** [comment]
I am having the same issue and I've copied the Python Quickstart code verbatim. The identify line you specified is part of this code but it is set to "voice_test". I'm just trying to see if this will work at all, so my question here is does the identity need to be changed in order for this to work? If so then what is a valid identity?

**Comment by miken01** [comment]
Never mind I figured out the issue. I had incorrect credentials for my push notification setup.

**Comment by bobiechen-twilio** [comment]
Hi @miken01 

Technically you are free to use any identity as long as the characters are within the ASCII char-set. In the other [issue thread](https://github.com/twilio/voice-quickstart-server-python/issues/11) you should find more explanation about how to configure the identity dynamically from the you iOS application.

cheers,
-bobie
