### ISSUE TITLE
voice : can create group voice ?

### ISSUE THREAD

**Issue by Base2526** [twilio/voice-quickstart-objc#94]
if can create group voice, have example ?
thx.

**Comment by bobiechen-twilio** [comment]
Hi @Base2526 

You can follow the steps in README, and modify the TwiML endpoint to generate a TwiML response instead of calling a number or client identity, but dialing into a conference. You'll find out more information in the [TwiML <Conference> verb](https://www.twilio.com/docs/api/twiml/conference).

-bobie

**Comment by Base2526** [comment]
Ok Thx. @bchen-twilio
