### ISSUE TITLE
Bluetooth headphones not recognized as audio device

### ISSUE THREAD

**Issue by nicolettemanas** [twilio/voice-quickstart-objc#95]
### Description
Hi Twilio team, 

I tried using the sample app initially used with a bluetooth device but the audio routes to the built in receiver/speaker once the call starts.

I have set all `toggleAudioRoute` to `NO` so the app should not override the audio route. 

As for the project without CallKit, I also added the options `AVAudioSessionCategoryOptionAllowBluetooth, AVAudioSessionCategoryOptionAllowBluetoothA2DP` when setting the session category and we are still getting the same results.

This happens whether the user with the bluetooth headphones is the receiver or the caller. 

#### Voice iOS SDK
2.0.2 via CocoaPods

#### Xcode
9.2

#### iOS Device
iPhone 6P+ (iOS 11), iPad mini (iOS 8.2)

**Comment by bobiechen-twilio** [comment]
Hi @nicolettemanas 

Thanks for reporting the issue.
First of all you can definitely remove the `toggleAudioRoute:YES` lines in your application since they are for quickstart demo purposes.
The issue you are experiencing is actually an expected behavior. TL;DR - use the "answer" button on the bluetooth headset to answer the incoming call and the audio will be routed to the bluetooth headset instead of having to change the audio route in the native call UI.
I actually figured out this behavior when I was driving. If you answer the incoming using the answer button on the steeling wheel then the audio will be routed to the bluetooth system of the car, but if you tap on the phone screen to answer the call, then the audio will be routed through either the built-in audio output or the speaker, and you will have to use the native call UI to change route if you want to.

Please give this a try and let us know if this helps.
Thanks
-bobie

**Comment by nicolettemanas** [comment]
Hi @bchen-twilio 

I see. That is exactly what is happening, sorry about that. 😅 

Thanks for the quick response,
Jean
